#!/usr/bin/env python
# Assignment 2
# Question 3
# Create a program that will play the “hearts and spades” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number (0000 - 9999) where the numbers should not repeat. For every digit that the user guessed correctly in the correct place, they have a “heart”. For every digit the user guessed correctly in the wrong place is a “spade.” Every time the user makes a guess, tell them how many “hearts” and “spades” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

# Say the number generated by the computer is 1035. An example interaction could look like this:
# Welcome to the Hearts and Spades Game!
# Enter a number:
# >>> 1234
# 2 heart, 0 spades
# >>> 1256
# 1 heart, 1 spade
# ...

import random

def heartsAndSpades():
  guessCount = 0
  guesses = List()
  print("Welcome to the Hearts and Spades Game!")
  NUMBER = random.randint(0, 9999)
  while True:
    try:
      guess = int(input("Please enter your guess :"))
      if isinstance(numberOfGuesses, int) is False or numberOfGuesses < 1:
        raise Exception
    except Exception:
      print("Please be sure to make your input as a positive integer number!")
    else:
      guessCount += 1
      #### TBD

heartsAndSpades()